version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cflp_api
    container_name: cflp_api_server
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./app:/app/app
    networks:
      - app_network
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: cflp_mysql_server
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=24Khjcmysql
      - MYSQL_DATABASE=CFLP
      - MYSQL_USER=dthghjc
      - MYSQL_PASSWORD=24Khjcmysql
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "dthghjc",
          "--password=24Khjcmysql",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data: